<?php
/**
 * Generates marketing_days_5_30_questions_seed.sql from build_marketing_days_5_30_seed.py (data only).
 * Run: C:\wamp_56_new\bin\php\php7.0.33\php.exe build_marketing_days_5_30_seed.php
 */
$root = __DIR__;
$pyPath = $root . DIRECTORY_SEPARATOR . 'build_marketing_days_5_30_seed.py';
$outPath = $root . DIRECTORY_SEPARATOR . 'marketing_days_5_30_questions_seed.sql';

$py = file_get_contents($pyPath);
if ($py === false) {
    fwrite(STDERR, "Cannot read: $pyPath\n");
    exit(1);
}

function aid($day)
{
    return $day + 3;
}

function escSql($s)
{
    return str_replace("'", "''", str_replace('\\', '\\\\', $s));
}

function arrayBracketContent($s, $fromPos)
{
    $lb = strpos($s, '[', $fromPos);
    if ($lb === false) {
        return null;
    }
    $len = strlen($s);
    $depth = 0;
    for ($i = $lb; $i < $len; $i++) {
        $c = $s[$i];
        if ($c === '[') {
            $depth++;
        } elseif ($c === ']') {
            $depth--;
            if ($depth === 0) {
                return substr($s, $lb + 1, $i - $lb - 1);
            }
        }
    }
    return null;
}

function parseCorrect($c)
{
    $c = strtoupper(trim($c));
    $mask = [0, 0, 0, 0];
    if (strlen($c) === 1 && strpos('ABCD', $c) !== false) {
        $idx = ord($c) - ord('A');
        $mask[$idx] = 1;
        return $mask;
    }
    for ($i = 0, $L = strlen($c); $i < $L; $i++) {
        $ch = $c[$i];
        if (strpos('ABCD', $ch) !== false) {
            $mask[ord($ch) - ord('A')] = 1;
        }
    }
    return $mask;
}

function lineMcq($row)
{
    $parts = explode('|', $row);
    if (count($parts) !== 6) {
        throw new Exception('Bad MCQ row: ' . $row);
    }
    list($q, $o1, $o2, $o3, $o4, $cor) = $parts;
    return [$q, [$o1, $o2, $o3, $o4], parseCorrect($cor)];
}

function emitMcq($sortOrder, $q, $opts, $mask)
{
    $eq = escSql($q);
    $sql = "INSERT INTO `ta_questions` (`assessment_id`,`question_type`,`question_text`,`points`,`coding_language`,`model_answer`,`text_keyword_pass_percent`,`coding_expected_output`,`sort_order`,`created_at`,`updated_at`)\n";
    $sql .= "VALUES (@aid,'mcq','{$eq}',1.00,NULL,NULL,50.00,NULL,{$sortOrder},NOW(),NOW());\n";
    $sql .= "SET @q := LAST_INSERT_ID();\n";
    $sql .= "INSERT INTO `ta_question_options` (`question_id`,`option_text`,`is_correct`,`sort_order`,`created_at`) VALUES\n";
    $lines = [];
    foreach ($opts as $i => $o) {
        $eo = escSql($o);
        $ic = (int) $mask[$i];
        $so = $i + 1;
        $lines[] = "(@q,'{$eo}',{$ic},{$so},NOW())";
    }
    $sql .= implode(",\n", $lines) . ";\n\n";
    return $sql;
}

function emitText($sortOrder, $q, $keywordsCsv)
{
    $eq = escSql($q);
    $ek = escSql($keywordsCsv);
    return "INSERT INTO `ta_questions` (`assessment_id`,`question_type`,`question_text`,`points`,`coding_language`,`model_answer`,`text_keyword_pass_percent`,`coding_expected_output`,`sort_order`,`created_at`,`updated_at`)\n"
        . "VALUES (@aid,'text','{$eq}',2.00,NULL,'{$ek}',50.00,NULL,{$sortOrder},NOW(),NOW());\n\n";
}

// --- Parse DAY13_TEXT ---
$pos = strpos($py, 'DAY13_TEXT = ');
if ($pos === false) {
    fwrite(STDERR, "DAY13_TEXT not found\n");
    exit(1);
}
$inner = arrayBracketContent($py, strpos($py, '[', $pos));
if ($inner === null) {
    fwrite(STDERR, "DAY13_TEXT bracket\n");
    exit(1);
}
preg_match_all('/\(\s*"([^"]+)"\s*,\s*"([^"]+)"\s*\)/', $inner, $m13, PREG_SET_ORDER);
$day13Text = [];
foreach ($m13 as $row) {
    $day13Text[] = [$row[1], $row[2]];
}

// --- Parse DAYS_MCQ[day] ---
$daysMcq = [];
for ($day = 5; $day <= 30; $day++) {
    $needle = 'DAYS_MCQ[' . $day . '] = ';
    $p = strpos($py, $needle);
    if ($p === false) {
        fwrite(STDERR, "Missing $needle\n");
        exit(1);
    }
    $inner = arrayBracketContent($py, strpos($py, '=', $p));
    if ($inner === null) {
        fwrite(STDERR, "Bad bracket for day $day\n");
        exit(1);
    }
    preg_match_all('/^"([^"]+)"\s*,?\s*$/m', $inner, $mm);
    $daysMcq[$day] = $mm[1];
}

$buf = '';
$buf .= "-- Marketing curriculum: Days 5-30 questions for ta_questions / ta_question_options\n";
$buf .= "-- assessment_id = day_number + 3 (Day 3=6, Day 4=7, so Day 5=8 ... Day 30=33)\n";
$buf .= "-- Ensure matching rows exist in ta_assessments before running.\n";
$buf .= "-- Day 13: 10 text (2 pts) + 20 MCQ (1 pt). Other days: 20 MCQ each.\n";
$buf .= "-- Re-running inserts duplicates — delete existing rows for that assessment_id first if needed.\n";
$buf .= "-- Generated by build_marketing_days_5_30_seed.php from build_marketing_days_5_30_seed.py\n\n";
$buf .= "START TRANSACTION;\n\n";

for ($day = 5; $day <= 30; $day++) {
    $a = aid($day);
    $buf .= "-- ========== Day {$day} (assessment_id={$a}) ==========\n";
    $buf .= "SET @aid := {$a};\n\n";

    if ($day === 13) {
        $so = 1;
        foreach ($day13Text as $pair) {
            $buf .= emitText($so, $pair[0], $pair[1]);
            $so++;
        }
        foreach ($daysMcq[13] as $row) {
            list($q, $opts, $mask) = lineMcq($row);
            $buf .= emitMcq($so, $q, $opts, $mask);
            $so++;
        }
    } else {
        $so = 1;
        foreach ($daysMcq[$day] as $row) {
            list($q, $opts, $mask) = lineMcq($row);
            $buf .= emitMcq($so, $q, $opts, $mask);
            $so++;
        }
    }
}

$buf .= "COMMIT;\n";

if (file_put_contents($outPath, $buf) === false) {
    fwrite(STDERR, "Cannot write $outPath\n");
    exit(1);
}

echo "Wrote $outPath\n";
