-- Optional: idempotent seed for `permissions` when upgrading an older database.
-- 1) Ensures Training & Learning keys exist (umbrella + per-sidebar-screen keys).
-- 2) Grants system_settings + permissions_edit to Admin/Manager so User Access + saving the permission grid work.
-- Safe to run multiple times (INSERT IGNORE).

INSERT IGNORE INTO `permissions` (`role_id`, `module`, `can_access`) VALUES
(1, 'training_lms', 1),
(1, 'training_lms_manage', 1),
(1, 'training_assessment', 1),
(1, 'training_assessment_manage', 1),
(1, 'training_assessment_take', 1),
(1, 'training_screen_ta_dashboard', 1),
(1, 'training_screen_ta_create', 1),
(1, 'training_screen_ta_import', 1),
(1, 'training_screen_ta_report', 1),
(1, 'training_screen_ta_team_progress', 1),
(1, 'training_screen_ta_my_tests', 1),
(1, 'training_screen_tl_hub', 1),
(1, 'training_screen_tl_module', 1),
(1, 'training_screen_tl_assignment', 1),
(1, 'training_screen_lms_admin', 1),
(1, 'training_screen_lms_submissions', 1),
(1, 'training_screen_lms_office_csv', 1),
(2, 'training_lms', 1),
(2, 'training_lms_manage', 1),
(2, 'training_assessment', 1),
(2, 'training_assessment_manage', 1),
(2, 'training_assessment_take', 1),
(2, 'training_screen_ta_dashboard', 1),
(2, 'training_screen_ta_create', 1),
(2, 'training_screen_ta_import', 1),
(2, 'training_screen_ta_report', 1),
(2, 'training_screen_ta_team_progress', 1),
(2, 'training_screen_ta_my_tests', 1),
(2, 'training_screen_tl_hub', 1),
(2, 'training_screen_tl_module', 1),
(2, 'training_screen_tl_assignment', 1),
(2, 'training_screen_lms_admin', 1),
(2, 'training_screen_lms_submissions', 1),
(2, 'training_screen_lms_office_csv', 1),
(3, 'training_lms', 1),
(3, 'training_assessment_take', 1),
(3, 'training_screen_ta_my_tests', 1),
(3, 'training_screen_tl_hub', 1),
(3, 'training_screen_tl_module', 1),
(3, 'training_screen_tl_assignment', 1),
(4, 'training_lms', 1),
(4, 'training_assessment_take', 1),
(4, 'training_screen_ta_my_tests', 1),
(4, 'training_screen_tl_hub', 1),
(4, 'training_screen_tl_module', 1),
(4, 'training_screen_tl_assignment', 1),
(1, 'system_settings', 1),
(2, 'system_settings', 1),
(1, 'permissions_edit', 1),
(2, 'permissions_edit', 1);
