-- =============================================================================
-- OPTIONAL: Migrate legacy unprefixed training assessment tables to ta_* names.
-- Only run if you already have assessments, questions, … and want prefixed names.
-- BACK UP YOUR DATABASE FIRST.
-- The PHP model supports both schemes; new installs typically use ta_* from
-- training_assessment_module.sql.
-- =============================================================================
--
-- MySQL / InnoDB: RENAME TABLE updates FK references in recent versions, but if
-- you hit errors, use the pattern: SET FOREIGN_KEY_CHECKS=0; … RENAME … ; SET FOREIGN_KEY_CHECKS=1;
--
-- Suggested order (children before parents is NOT required for RENAME — rename
-- in any order that succeeds; if a FK blocks, temporarily disable checks):
--
--   SET FOREIGN_KEY_CHECKS = 0;
--   RENAME TABLE `assessments` TO `ta_assessments`;
--   RENAME TABLE `assessment_users` TO `ta_assessment_users`;
--   RENAME TABLE `questions` TO `ta_questions`;
--   RENAME TABLE `question_options` TO `ta_question_options`;
--   RENAME TABLE `user_answers` TO `ta_user_answers`;
--   RENAME TABLE `results` TO `ta_results`;
--   SET FOREIGN_KEY_CHECKS = 1;
--
-- After rename, verify foreign keys (example — adjust constraint names to match your DB):
--   SHOW CREATE TABLE `ta_questions`;
--   SHOW CREATE TABLE `ta_assessment_users`;
-- If any FK still references old table names, run ALTER TABLE … DROP FOREIGN KEY …
-- then ADD CONSTRAINT … REFERENCES `ta_…` (…).
--
-- Do NOT run this on a fresh install that already created ta_* only.
-- =============================================================================
