<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo esc_view($branding->portal_title); ?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><style>:root{--bs-primary:<?php echo esc_view($branding->primary_color ?: '#0d6efd'); ?>}</style></head><body class="bg-light">
<nav class="navbar navbar-dark bg-primary"><div class="container"><span class="navbar-brand"><?php echo esc_view($branding->portal_title); ?></span><a class="btn btn-sm btn-outline-light" href="<?php echo site_url('logout'); ?>">Logout</a></div></nav>
<div class="container py-4"><h1 class="h4">Hello, <?php echo esc_view($client->full_name); ?></h1>
<?php if ($branding->welcome_message): ?><p class="text-muted"><?php echo nl2br(esc_view($branding->welcome_message)); ?></p><?php endif; ?>
<div class="row g-3">
<div class="col-md-6"><div class="card"><div class="card-header">Next sessions</div><ul class="list-group list-group-flush"><?php foreach ($sessions as $s): if ($s->status!=='scheduled') continue; ?><li class="list-group-item small"><?php echo date('d M H:i', strtotime($s->scheduled_at)); ?> — <?php echo esc_view($s->title); ?><?php if ($s->notes_client): ?><br><span class="text-muted"><?php echo esc_view($s->notes_client); ?></span><?php endif; ?></li><?php endforeach; ?></ul></div></div>
<div class="col-md-6"><div class="card"><div class="card-header">Goals</div><ul class="list-group list-group-flush"><?php foreach ($goals as $g): ?><li class="list-group-item small"><?php echo esc_view($g->title); ?> — <?php echo (int)$g->progress_pct; ?>%</li><?php endforeach; ?></ul></div></div>
<div class="col-md-6"><div class="card"><div class="card-header">Homework</div><ul class="list-group list-group-flush"><?php foreach ($homework as $h): ?><li class="list-group-item small"><?php echo esc_view($h->title); ?> (<?php echo $h->status; ?>) <?php if ($h->status==='pending'): ?><?php echo form_open('coaching-portal/homework-done/'.$h->id, ['class'=>'d-inline']); ?><button class="btn btn-link btn-sm p-0">Mark done</button><?php echo form_close(); ?><?php endif; ?></li><?php endforeach; ?></ul></div></div>
<div class="col-md-6"><div class="card"><div class="card-header">Pending payments</div><ul class="list-group list-group-flush"><?php if (empty($pending_installments)): ?><li class="list-group-item text-muted small">None</li><?php else: foreach ($pending_installments as $inst): ?><li class="list-group-item small">₹<?php echo number_format($inst->amount,2); ?> <a href="<?php echo site_url('coaching-payments/pay/'.$inst->id); ?>" class="btn btn-sm btn-primary float-end">Pay</a></li><?php endforeach; endif; ?></ul></div></div>
<div class="col-md-6"><div class="card"><div class="card-header">Resources</div><ul class="list-group list-group-flush"><?php foreach ($resources as $res): if (!$res->visible_to_client) continue; ?><li class="list-group-item small"><?php if ($res->file_path): ?><a href="<?php echo base_url($res->file_path); ?>" target="_blank"><?php echo esc_view($res->title); ?></a><?php else: ?><a href="<?php echo esc_view($res->external_url); ?>" target="_blank"><?php echo esc_view($res->title); ?></a><?php endif; ?></li><?php endforeach; ?></ul></div></div>
</div></div></body></html>
