#!/usr/bin/env python3
"""
Generate subscription_builder_seed.sql from tab-separated source data.

Usage:
  python tools/generate_subscription_builder_seed.py database/subscription_builder_source.tsv

Column order in source TSV:
  Plan, Industry, Module, Feature, Details,
  Per Item Set Up Charges, Item Unit, Common Set Up Fees,
  Per Item Per Month Maintenances
"""

import re
import sys
from pathlib import Path


def sql_escape(value):
    if value is None:
        return 'NULL'
    text = str(value).strip()
    if text == '':
        return 'NULL'
    return "'" + text.replace('\\', '\\\\').replace("'", "\\'") + "'"


def sql_decimal(value):
    if value is None:
        return 'NULL'
    text = str(value).strip().replace(',', '')
    if text == '':
        return 'NULL'
    try:
        float(text)
    except ValueError:
        return 'NULL'
    return text


def parse_row(line):
    line = line.rstrip('\n\r')
    if not line.strip():
        return None
    parts = line.split('\t')
    while len(parts) < 9:
        parts.append('')
    parts = parts[:9]
    plan, industry, module, feature, details, per_item_setup, item_unit, common_setup, per_month = parts
    if plan.strip().lower() == 'plan':
        return None
    if not plan.strip() and not industry.strip() and not feature.strip():
        return None
    return {
        'plan': plan.strip(),
        'industry': industry.strip(),
        'module': module.strip(),
        'feature': feature.strip(),
        'details': details.strip(),
        'per_item_set_up_charges': per_item_setup.strip(),
        'item_unit': item_unit.strip(),
        'common_set_up_fees': common_setup.strip(),
        'per_item_per_month_maintenances': per_month.strip(),
    }


def main():
    if len(sys.argv) < 2:
        print('Usage: python tools/generate_subscription_builder_seed.py <source.tsv>', file=sys.stderr)
        sys.exit(1)

    source = Path(sys.argv[1])
    if not source.exists():
        print(f'Source file not found: {source}', file=sys.stderr)
        sys.exit(1)

    rows = []
    for line in source.read_text(encoding='utf-8-sig').splitlines():
        parsed = parse_row(line)
        if parsed:
            rows.append(parsed)

    if not rows:
        print('No data rows found.', file=sys.stderr)
        sys.exit(1)

    out_path = source.parent / 'subscription_builder_seed.sql'
    lines = [
        '-- Auto-generated by tools/generate_subscription_builder_seed.py',
        'SET NAMES utf8;',
        '',
        'DELETE FROM `subscription_builder`;',
        '',
    ]

    batch = []
    for row in rows:
        values = ', '.join([
            sql_escape(row['plan']),
            sql_escape(row['industry']),
            sql_escape(row['module']),
            sql_escape(row['feature']),
            sql_escape(row['details']),
            sql_decimal(row['per_item_set_up_charges']),
            sql_escape(row['item_unit']),
            sql_decimal(row['common_set_up_fees']),
            sql_decimal(row['per_item_per_month_maintenances']),
            'NOW()',
            'NOW()',
        ])
        batch.append(f'({values})')
        if len(batch) >= 100:
            lines.append(
                'INSERT INTO `subscription_builder` '
                '(`plan`,`industry`,`module`,`feature`,`details`,'
                '`per_item_set_up_charges`,`item_unit`,`common_set_up_fees`,'
                '`per_item_per_month_maintenances`,`created_at`,`updated_at`) VALUES'
            )
            lines.append(',\n'.join(batch) + ';')
            lines.append('')
            batch = []

    if batch:
        lines.append(
            'INSERT INTO `subscription_builder` '
            '(`plan`,`industry`,`module`,`feature`,`details`,'
            '`per_item_set_up_charges`,`item_unit`,`common_set_up_fees`,'
            '`per_item_per_month_maintenances`,`created_at`,`updated_at`) VALUES'
        )
        lines.append(',\n'.join(batch) + ';')
        lines.append('')

    out_path.write_text('\n'.join(lines), encoding='utf-8')
    print(f'Wrote {len(rows)} rows to {out_path}')


if __name__ == '__main__':
    main()
