<?php $this->load->view('partials/header', ['title' => 'Edit Rule']); ?>
<div class="container-fluid py-3"><h1 class="h4 fw-bold mb-3"><?php echo $item?'Edit':'New'; ?> rule</h1>
<div class="card shadow-soft"><div class="card-body"><form method="post"><?php echo form_hidden($this->security->get_csrf_token_name(), $this->security->get_csrf_hash()); ?>
<div class="row g-3"><div class="col-md-4"><label class="form-label">Code</label><input name="code" class="form-control" required value="<?php echo $item?htmlspecialchars($item->code):''; ?>"></div><div class="col-md-8"><label class="form-label">Name</label><input name="name" class="form-control" required value="<?php echo $item?htmlspecialchars($item->name):''; ?>"></div></div>
<div class="mb-3 mt-3"><label class="form-label">Trigger event</label><input name="trigger_event" class="form-control" required value="<?php echo $item?htmlspecialchars($item->trigger_event):''; ?>"></div>
<div class="mb-3"><label class="form-label">Condition JSON</label><textarea name="condition_json" class="form-control" rows="2"><?php echo $item?htmlspecialchars($item->condition_json):'{}'; ?></textarea></div>
<div class="row g-3"><div class="col-md-3"><label class="form-label">Points</label><input type="number" step="0.01" name="points" class="form-control" value="<?php echo $item?(float)$item->points:10; ?>"></div><div class="col-md-3"><label class="form-label">Max/day</label><input type="number" name="max_per_day" class="form-control" value="<?php echo $item && $item->max_per_day!==null?(int)$item->max_per_day:''; ?>"></div><div class="col-md-3"><label class="form-label">Requires approval</label><select name="requires_approval" class="form-select"><option value="0">No</option><option value="1" <?php echo ($item && $item->requires_approval)?'selected':''; ?>>Yes</option></select></div><div class="col-md-3"><label class="form-label">Active</label><select name="is_active" class="form-select"><option value="1">Yes</option><option value="0" <?php echo ($item && !$item->is_active)?'selected':''; ?>>No</option></select></div></div>
<div class="mb-3 mt-3"><label class="form-label">Description</label><textarea name="description" class="form-control" rows="2"><?php echo $item?htmlspecialchars($item->description):''; ?></textarea></div>
<button class="btn btn-primary">Save</button> <a href="<?php echo site_url('rewards/rules'); ?>" class="btn btn-outline-secondary">Cancel</a>
</form></div></div></div>
<?php $this->load->view('partials/footer'); ?>
